In [ ]:
#creating a 1D array usig numpy

import numpy as np

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
#creating a 2D array

import numpy as np

arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(type(arr2))
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
(2, 5)


In [12]:
#creating array with arange() function

import numpy as np

arr3=np.arange(0,12,1).reshape(3,4)
print(arr3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
#1s matrix

import numpy as np

arr4=np.ones((3,4))
print(arr4)
print("\n")

#0s matrix
arr5=np.zeros((3,4))
print(arr5)
print("\n")

#identity matrix

arr6=np.eye(3)
print(arr6)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
#functions in array
import numpy as np
arr7=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr7)
print(arr7.shape)
print(arr7.ndim)
print(arr7.size)
print(arr7.dtype)
print(arr7.itemsize)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
2
10
int64
8


In [31]:
#vectorization in array
import numpy as np
arr8=np.array([1,2,3,4,5])
arr9=np.array([6,7,8,9,10])

print(arr8+arr9)
print(arr8*arr9)
print(arr8/arr9)
print(arr8-arr9)

[ 7  9 11 13 15]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[-5 -5 -5 -5 -5]


In [36]:
#more functions

import numpy as np

arr=np.array([1,2,3,4,5])

#square root
print(np.sqrt(arr))

#expoential
print(np.exp(arr))

#sin
print(np.sin(arr))

#cos
print(np.cos(arr))

#tan
print(np.tan(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [37]:
#slicing and indexing in 

import numpy as np

arr10=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr10)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [57]:
#slicing

arr10[1:,3:]
arr10[0:2,2:4]
arr10[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [65]:
#indexing

print(arr10[0][3])
print(arr10[2][2])
print(arr10[-3][-2])

4
13
4


In [66]:
#modify array items

arr10[0][3]=40
print(arr10)

[[ 1  2  3 40  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [76]:
#logical operations

import numpy as np

arr11=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

print(arr11>5)
print(arr11<5)
arr11[(arr11>=5) & (arr11<=10)]

[False False False False False  True  True  True  True  True  True  True
  True  True]
[ True  True  True  True False False False False False False False False
 False False]


array([ 5,  6,  7,  8,  9, 10])